hyperledger-labs/go-perun

client/client.go
client/client_role_test.go
client/proposal.go
client/test/alice.go
client/test/bob.go
client/test/proposer.go
client/update.go

When interacting on a channel directly after channel opening, it can happen that the other side has not yet completed the channel opening procedure. In this case, there was a notice about a channel update for an unknown channel and the update would never go through. This change fixes this bug by caching the first channel update until the channel opening is complete.

Cache first channel update

---

README.md

The security disclaimer was not updated in a long time. Our software has progressed since then.

:memo: [README] Update security disclaimer

---

client/proposal.go
client/proposal_test.go
client/update.go

I have renamed `PeerRejectedProposalError` to `PeerRejectedError`, so that the same error type can be used when peer rejects an update as well.
The other option could be to use two error types. Request your feedback on this.

Extend PeerRejectedProposalError for rejected updates

---

client/channel.go
client/client_test.go
client/test/role.go
client/update.go

Since Channel.State() can not be called from an Update handler and
having the current state in the ChannelUpdate does not make sense,
i moved added it as argument to HandleUpate.
Closes #15

Add current State to HandleUpdate.

---

client/proposalmsgs.go

:memo: [client] Document parameters of NewLedgerChannelProposal

---

client/proposal_internal_test.go

An inconsistent LedgerChannelProposal may have been generated because
the allocation was generated independent of the number of participants.
Signed-off-by: Matthias Geihs <matthias@perun.network>

:bug: [client] Fix NewRandomLedgerChannelProposal

---

channel/params.go
channel/params_test.go

When deserializing parameters, it must be checked whether the ID is
correct. Otherwise we might end up with an inconsistent Params object.
Signed-off-by: Matthias Geihs <matthias@perun.network>
Closes #56

:lock: [channel] Check ID after decoding parameters

---

client/init.go

Enable default logging with level 'Warning' to increase usability.
Closes #64

Enable logging per default

---

backend/ethereum/channel/funder_test.go
channel/funder.go
channel/funder_test.go

- Previously, the function returned pointer to an error. Update it to
return a value.
- It is idiomatic to return error types as values. The change also
ensures this func is consistent with constructors for other error
types.
Closes #73.
Signed-off-by: Manoranjith <ponraj.manoranjitha@in.bosch.com>

:boom: [channel] Update NewFundingTimeoutError to return a value

---

backend/ethereum/channel/timeout_test.go

Make the `TestBlockTimeout_Wait/normalWait` stable for CI.  
Example failure: https://github.com/hyperledger-labs/go-perun/runs/2692568029?check_suite_focus=true#step:4:89

[backend/eth/channel] Fix BlockTimeout test.

---

backend/ethereum/channel/funder.go
backend/ethereum/subscription/doc.go
backend/ethereum/subscription/eventsub.go
backend/ethereum/subscription/eventsub_test.go

Add generic event subs in preparation for https://github.com/hyperledger-labs/go-perun/issues/19.

Generic events sub

---

client/channelconn.go
client/clientconn.go

Log the message type instead of a binary blob.
Closes #95

Log message type.

---

backend/ethereum/channel/test/simulated.go
backend/ethereum/channel/test/simulated_test.go

Introduces two functions: `StartMining(interval)` and `StopMining`.  
Can be used to simulate a ticking blockchain.  
Closes #103

Add Auto-mining to SimulatedBackend

---

backend/ethereum/channel/asset.go
backend/ethereum/channel/asset_test.go

- Contract code at adjudicator address is not validated because, the
it is passed by the caller, hence it is the responsibility of the
caller to provide a valid address.
Resolves #109.

:boom: [backend/eth/channel] Remove validation of adj in validateAssettHolder

---

backend/ethereum/bindings/abi.go
backend/ethereum/channel/adjudicator.go
backend/ethereum/channel/conclude.go
backend/ethereum/channel/funder.go
backend/ethereum/channel/subscription.go
backend/ethereum/channel/test/adjudicator.go
backend/ethereum/channel/withdraw.go
backend/ethereum/subscription/eventsub.go
backend/ethereum/subscription/eventsub_test.go

Use EventSub instead of Filter/Watch.

---

pkg/test/concurrent.go
pkg/test/concurrent_external_test.go
pkg/test/goexit.go

ConcurrentT can now be constructed with an optional context which will cause all stages and waiting operations to fail on expiry.
I diverged from the issue's initial plan, because introducing custom contexts would have made the ConcurrentT object harder to use correctly. Now, there is only one context per ConcurrentT, and not one per wait call. The only adaption needed to use the new feature is to swap out the ConcurrentT's constructor in tests.
Closes #110.

:sparkles: [pkg/test] Add context to ConcurrentT.

---

backend/ethereum/channel/backend_test.go

Test the HashState function instead of CalcID, which is already being tested in testCalcID.

Fix testHashState

---

backend/ethereum/channel/funder.go
backend/ethereum/channel/funder_test.go
backend/ethereum/channel/test/setup.go

- As these methods provide convenience for the user (to register assets after funder is initialized) and are not required by the framework itself for the process of funding, they are not added to the `Funder` interface.
- Use the `RegisterAsset` method in place of `WithDepositor`, as the newly added method provides the same functionality without making a copy of the funder.
- Also, fixed a bug in `funder_test.go`. See the last before commit for details.

Add functions to register new assets in ethereum funder implementation

---

client/update.go

Fixes a bug where `updateGeneric` discarded a `PeerRejectedError` and replaced it with a different error.
Signed-off-by: Matthias Geihs <matthias@perun.network>

:bug: [client] Fix update error propagation

---

backend/ethereum/channel/contractbackend.go

Fix is attempted using approach 1 suggested in #62.

Fix tx nonce mismatch error: approach 1

---

backend/ethereum/channel/backend.go
backend/ethereum/channel/subscription.go
channel/adjudicator.go
client/adjudicate.go
client/client_role_test.go
client/client_test.go
client/test/backend.go
client/test/role.go
client/virtual_channel.go
client/virtual_channel_test.go

After splitting up the Virtual channel PR into several smaller, but still not small, PRs, this should now be the last one of that series. It contains:
- Virtual channel watching
- Virtual channel dispute tests
Closes #82

Virtual channel watching and dispute test (Last part of large Virtual Channel PR)

---

.golangci.yml

- Enable default linters
- Remove `fast: false`, because it is the default value.
- Remove golint because deprecated.
Owner suggests to use staticcheck or go vet.
We already use staticcheck.
- Remove interfacer because deprecated
Owner mentions that tool is error prone.
- Remove scopelint because deprecated, add exportloopref
Owner suggests to use looppointer or exportloopref instead.
Closes #145

:rotating_light: [golangci] Revise configuration

---

client/adjudicate.go
client/test/channel.go
client/test/progression.go
client/testchannel.go
client/virtual_channel_test.go

143 settle implicit register

---

backend/ethereum/channel/conclude.go

:bug: [backend/eth] conclude after progression into final

---

backend/ethereum/channel/reorg_test.go
backend/ethereum/channel/test/simulated.go
backend/ethereum/channel/test/tokensetup.go

Introduces a `Reorg` function. Example can be found in #105.  
Im not quite sure here with the testing, if it is too complicated, we could leave it for later.  
<s>It sadly uses a replace in the `go.mod`, lets see if it works in the CI.</s>
Closes #105

Add Reorg to SimulatedBackend

---

backend/ethereum/channel/adjudicator_test.go
backend/ethereum/channel/conclude_test.go
backend/ethereum/channel/contractbackend.go
backend/ethereum/channel/contractbackend_test.go
backend/ethereum/channel/funder_test.go
backend/ethereum/channel/register_test.go
backend/ethereum/channel/reorg_test.go
backend/ethereum/channel/test/setup.go
backend/ethereum/channel/withdraw_test.go
backend/ethereum/client/dispute_test.go
backend/ethereum/client/happy_test.go
backend/ethereum/client/progression_test.go
backend/ethereum/subscription/init_test.go
client/client_role_test.go
client/test/role.go

Confirm TX with Finality Depth

---

backend/ethereum/subscription/resistanteventsub.go
backend/ethereum/subscription/resistanteventsub_test.go

Adds the `ResistantEventSub` type.  
Also introduced a convenience function `Subscribe(ctx context.Context, cr ethereum.ChainReader, contract *bind.BoundContract, eFact EventFactory, startBlockOffset, confirmations uint64) (*ResistantEventSub, error)` which makes it easier to create a resistant sub.  
I am not happy with the arguments of `Subscribe` yet, since it are so many.
Closes #40 
Draft until #105 is closed

Resistant event subs

---

backend/ethereum/channel/conclude.go
backend/ethereum/channel/funder.go
backend/ethereum/channel/subscription.go
backend/ethereum/channel/withdraw.go
backend/ethereum/client/init_test.go
backend/ethereum/subscription/resistanteventsub.go
backend/ethereum/subscription/resistanteventsub_test.go

Uses resistant event confirmation on *go-perun* in all locations.  
Currently i am having trouble with the `AdjudicatorSub`, which seems to make some end-to-end tests fail.  
Funder and Adjudicator tests themselves seem to work.
Closes #85 
Draft until #40 and #97 are closed.

Integrate Resistant Event Subs

---

channel/funder.go

Closes #165 
Also addresses that the funder interface could be used for off-chain funding, while the docu explicitly mentions only on-chain funding.

:memo: [channel] Update Funder docu

---

backend/ethereum/channel/adjudicator_test.go
backend/ethereum/channel/conclude_test.go
backend/ethereum/channel/register_test.go
backend/ethereum/channel/subscription.go
backend/ethereum/channel/test/adjudicator.go
backend/ethereum/channel/withdraw_test.go
channel/adjudicator.go
client/adjudicate.go
client/test/backend.go
client/test/mallory.go
client/virtual_channel.go

- Previously, Adjudicator.Subscribe was taking channel.Params, while it
was using only the ID contained in the params.
- So, modified the API to take only the required parameter.
Resolves #173.

 Modify Adjudicator.Subscribe to take channel.ID instead of channel.Params

---

pkg/test/cloning.go

`InterfaceData()` is deprecated and returns unreadable data in the
current go version. Use `Interface()` instead.

[pkg/test] Remove deprecated function.

---

backend/ethereum/channel/adjudicator_test.go
backend/ethereum/channel/backend.go
backend/ethereum/channel/conclude_test.go
backend/ethereum/channel/register_test.go
backend/ethereum/channel/withdraw_test.go
backend/sim/channel/backend.go
channel/backend.go
channel/machine.go
channel/persistence/statemachine_test.go
channel/persistence/test/channel.go
channel/statemachine.go
channel/test/channeltest.go
channel/test/randomizer.go
client/sync.go
client/virtual_channel.go
client/virtual_channel_settlement.go

Closes #195 #190 
Depends on #191

Channel.Backend: Remove Params from Sign and Verify

---

backend/ethereum/wallet/hd/wallet_test.go
backend/ethereum/wallet/keystore/wallet_test.go
backend/ethereum/wallet/simple/wallet_test.go
backend/sim/wallet/wallet_internal_test.go
wallet/address.go
wallet/backend.go
wallet/test/walletbench.go
wallet/test/wallettest.go

Closes #193 
The variable name was suggesting that it can always be initialized with `Address.Bytes`, but the tests were assuming that the address is decodable, which is not necessarily true for `Address.Bytes`. In particular, note that the length of `Address.Bytes` can be retrieved using the `len` operator, while the length of an encoded address must either be known in advance or contained in the encoding.

193 rename wallettest variable

---

backend/ethereum/client/dispute_test.go
backend/ethereum/client/happy_test.go
backend/ethereum/client/progression_test.go
backend/ethereum/client/test/doc.go
backend/ethereum/client/test/setup.go
client/client_role_test.go
client/test/backend.go
client/test/role.go
client/virtual_channel_test.go

Closes #200 
Introduces a balance reader interface for the generic client tests.
(Also moves `func makeRoleSetups` to a more suitable location.)

balance reader interface

---

backend/ethereum/channel/conclude_test.go
client/adjudicate.go

Closes #207 
Closes #206 
Also fixes another issue where `ensureRegistered` would fail because the channel is registered twice.

207 fix ensure registered

---

backend/ethereum/channel/backend.go

Function `FromEthState` did not set the App correctly on a decoded state.
Relates to #226

backend/eth/channel: Fix state app decoding

---

backend/ethereum/channel/backend.go
channel/allocation.go
channel/machine.go
client/test/role.go
client/virtual_channel_settlement.go
client/virtual_channel_test.go

Goal: Make Allocation easier to setup and modify.
Closes #63

🚸  Allocation helpers

---

backend/sim/wallet/address.go
backend/sim/wallet/wallet_internal_test.go

- Don't discard bytes anymore when encoding a sim address.  
Closes #261

[sim] Use all bytes for Addr.String()

---

backend/ethereum/channel/backend_test.go

- Cover `ToEthState` and `FromEthState` with unit a test
Closes #226

[backend/eth/ch] Test (To|From)EthState encoding.

---

apps/payment/app.go
apps/payment/resolver_internal_test.go
backend/ethereum/channel/backend.go
channel/actionmachine.go
channel/allocation.go
channel/app.go
channel/mock_app.go
channel/mock_app_internal_test.go
channel/noapp.go
channel/state.go
client/proposalmsgs.go
pkg/io/equal_binary.go
pkg/io/serialize.go

Change Data and Action type from Encoder to binary.(Un)marshaler. 
Relates to #233 (Step 1.2) and closes #257.

Refactor Data and Action Type

---

.golangci.yml
backend/ethereum/channel/test/adjudicator.go
backend/ethereum/channel/test/simulated.go
channel/persistence/test/channel.go
channel/persistence/test/persistrestorertest.go
client/channelconn.go
client/proposal.go
client/update.go
client/virtual_channel.go
client/virtual_channel_settlement.go
watcher/local/watcher.go
wire/cache.go
wire/cache_internal_test.go
wire/relay.go
wire/relay_internal_test.go

Enable context check linter

---

client/adjudicate.go
client/test/progression.go

Client: Adapt ForceUpdate to Update

---

backend/ethereum/channel/backend.go
backend/ethereum/wallet/hd/wallet_test.go
backend/ethereum/wallet/keystore/wallet_test.go
backend/ethereum/wallet/simple/wallet_test.go
backend/sim/wallet/wallet_internal_test.go
channel/actionmachine.go
channel/params.go
client/proposal.go
wallet/test/address.go
wallet/test/wallet.go
wallet/test/walletbench.go

This PR covers step 4 described in #233.
Note: To be merged after #297.

Use UnmarshalBinary and MarshalBinary for converting to/from Binary form

---

client/proposalmsgs.go
client/proposalmsgs_test.go

- Previously, the proposal ID for a virtual channel was generated using
the ProposalID method defined on BaseChannelProposal.
- Hence, not all parameters of the virtual channel proposal were used.
- Fix it by defining a ProposalID method on the virtual channel.
- Also, remove the ProposalID method on the BaseChannelProposal, as it
is not needed.
Fixes #299.

Fix virtual channel proposal id generation

---

client/channel.go
client/client.go
client/proposal.go
client/proposal_internal_test.go
client/proposalmsgs.go
client/proposalmsgs_test.go
client/sync.go
client/syncmsgs.go
client/test/randomproposal.go
client/test/role.go
client/update.go
client/updatemsgs.go
client/updatemsgs_internal_test.go
client/virtual_channel.go
client/virtual_channel_settlement.go
client/virtual_channel_test.go

- Consistently use the pattern `<message-name>Msg` for all message types.
- Export the unexported message types, so that newer wire serialization adapters can define functions for serializing/de-serializing these messages.
Closes #302

Rename wire message types

---

README.md
channel/machine.go
channel/statemachine.go
client/adjudicate.go
client/test/channel.go
client/test/progression.go
client/update.go
client/virtual_channel_test.go

Related to #155 
Instead of changing the API drastically, improve documentation.

:boom: Channel.Update/ForceUpdate: updater no longer returns error

---

backend/ethereum/channel/funder.go
backend/ethereum/channel/funder_test.go

`TestFunding_PeerTimeout` failed sometimes, this was due to an event race in the logic of the funder's `waitForFundingConfirmation` function: it was handling the same context's `Done()` event in two different `select` branches.
In this MR, I properly prioritize the `select` branches so that the race is resolved.

Fix funder timeout tests

---

backend/ethereum/channel/conclude_test.go
backend/ethereum/channel/test/simulated.go
backend/ethereum/subscription/resistanteventsub.go

* Stabilise reorg resistant subscription tests, although it does not cause the inherent problem that caused the tests to fail. Fixing that would be way more involved.
* Fix bug in Adjudicator test: challenge duration (is used as timeout for the funding transactions) was selected in *[0,3600)*, fixed to *[200,3600)* now, to guarantee enough time for funding.

Fix CI fails

---

client/proposalmsgs_test.go
client/syncmsgs_test.go
client/test/proposalmsgs.go
client/test/syncmsgs.go
client/test/updatemsgs.go
client/updatemsgs_test.go
wire/account_test.go
wire/controlmsgs_test.go
wire/test/msgstest.go

- Refactor the tests to use generic test functions.
- In preparation for extending these tests to newer wire serialization
adapters.
- Also, use random string for reason field in shutdowm message test.

Refactor message serialization tests

---

backend/ethereum/channel/contractbackend.go
backend/ethereum/channel/contractbackend_test.go
backend/ethereum/channel/funder_test.go
backend/ethereum/channel/test/setup.go
backend/ethereum/channel/test/simulated.go
backend/ethereum/channel/test/tokensetup.go
backend/ethereum/channel/test/transactor.go
backend/ethereum/subscription/eventsub_test.go
backend/ethereum/wallet/hd/transactor_test.go
backend/ethereum/wallet/keystore/transactor_test.go
backend/ethereum/wallet/simple/transactor_test.go

- eth/channel: Use types.LatestSigner for all sim backend tests
- Before, `types.EIP155Signer`s were created in many different places.
It is recommended by the geth folks to use `types.LatestSigner` instead.
This was streamlined an there's now a common `channel/test.SimSigner` that
can always be used together with the simulated backend.
- `FundAddress` and `Test_ConfirmTransaction` were adapted to use the
new `types.DynamicFeeTx`.
- The unused `test.GasLimit` variable was deleted.
- The `test.GasPrice` variable was renamed to `InitialGasBaseFee` and its
description updated.
- eth/channel: Don't set `GasPrice` in `ContractBackend.NewTransactor`
- Setting `TransactOpts.GasPrice` forces the transactions to be sent as a
legacy transaction, instead of a type 2 EIP1559, which results in much …

Use LatestSigner and don't set GasPrice in ContractBackend

---

client/proposalmsgs_test.go
wire/controlmsgs_test.go
wire/encode.go
wire/net/bus.go
wire/net/bus_test.go
wire/net/dialer.go
wire/net/endpoint_internal_test.go
wire/net/endpoint_registry.go
wire/net/endpoint_registry_external_test.go
wire/net/endpoint_registry_internal_test.go
wire/net/exchange_addr_internal_test.go
wire/net/ioconn.go
wire/net/listener.go
wire/net/simple/dialer.go
wire/net/simple/dialer_internal_test.go
wire/net/simple/listener.go
wire/net/simple/listener_internal_test.go
wire/net/test/connhub.go
wire/net/test/connhub_internal_test.go
wire/net/test/dialer.go
wire/net/test/dialer_internal_test.go
wire/net/test/listener.go
wire/net/test/listener_internal_test.go
wire/net/test/pipeconn.go
wire/perunio/serializer/serializer.go
wire/perunio/test/msgtest.go
wire/protobuf/serializer.go
wire/protobuf/serializer_test.go
wire/protobuf/test/serializertest.go
wire/test/serializinglocalbus.go

This PR proposes to initialize the wire encoding explicitly when needed, instead of setting it via an implicit import. This allows a user to have a better understanding which component uses which encoding and when setting an encoding is not necessary (for example, in case of using a local bus).

Initialize wire encoding explicitly

---

channel/params.go
wallet/address.go
wallet/address_test.go

- wallet: Add CloneAddress(es)
- channel: Use CloneAddresses in Params.Clone
It is convenient for users of the go-perun lib to have means for `wallet.Address` cloning. It was already done in `Params.Clone` so I extracted the functionality into the `wallet` package. No interfaces etc changed.

wallet.CloneAddress(es)

---

client/adjudicate.go
client/appchannel_test.go
client/client_persistence_test.go
client/client_role_test.go
client/happy_test.go
client/test/progression.go

Adds an app-channel test to go-perun core, which was previously only run in the Ethereum backend.

App channel test

---

client/test/carol.go

This removes the dependency on the availability of `e.State` in the app channel tests, which is a feature otherwise only necessary for the virtual channel protocol.

Dispute test: Use e.Version instead e.State.Version

---

client/appchannel_test.go
client/client_persistence_test.go
client/client_role_test.go
client/dispute_test.go
client/happy_test.go
client/subchannel_dispute_test.go
client/subchannel_happy_test.go
client/test/carol.go
client/test/channel.go
client/test/mallory.go
client/test/persistence.go
client/test/progression.go
client/test/proposer.go
client/test/responder.go
client/test/role.go
client/test/subchannel.go
client/test/subchannel_dispute.go
client/virtual_channel_test.go

Client tests involve concurrency. t.FailNow is not available there.
That's why we often used assert instead of require. Now we can use
role.Require.

Client tests: fail on error

---

channel/mock_app.go
channel/persistence/keyvalue/restorer.go
channel/persistence/test/channel.go
channel/persistence/test/persistrestorertest.go
client/channelconn.go
client/proposal.go
client/proposalopts.go
client/sync.go
client/test/backend.go
client/update.go
watcher/local/watcher_test.go
wire/cache.go
wire/relay.go

My local version of golangci for some reason reports more than our CI. Goal of this PR: Satisfy local and remote golangci.
depends on #341

Satisfy linter

---

channel/state.go

For verifying signatures, we require that the State.Data encoding is stable, that is, `E(data) = E(D(E(data)))`. This PR proposes to specify that requirement at the Interface.

📝 channel: Improve Data documentation

---

client/appchannel_test.go
client/client_persistence_test.go
client/client_role_test.go
client/dispute_test.go
client/happy_test.go
client/subchannel_dispute_test.go
client/subchannel_happy_test.go
client/test/persistence.go
client/test/proposer.go
client/test/responder.go
client/test/role.go
client/virtual_channel_test.go

Previously, we introduced error channels for immediate error handling.
However, this was done at the expense of requiring an additional error
channel parameter during testing setup, which made it more complicated
to setup a client test. Now the error channels are kept only with the
role and the changes to the setup function parameters are reverted.

:art: client/test: Reduce setup complexity

---

channel/funder.go
client/client_role_test.go
client/failing_funding_test.go
client/proposal.go
client/test/backend.go
client/test/handler.go
client/test/multiledger.go
client/virtual_channel_test.go

This is the second implementation variant where the `ProposeChannel` method does not automatically settle the channel after a failed funding but the client itself has to take care of this.

Settle channel when funding fails (Variant B)

---

client/update.go
client/update_internal_test.go

Our update handling logic allowed potentially left the channel state machine unlocked if not used correctly. Correct usage was neither documented, nor enforced. This PR proposes an update handling mechanism where the channel machine is only unlocked once the update handler is done.
Closes #270

Handle update locked

---

client/test/role.go
watcher/local/watcher.go

In rare occasions, the local watcher was running into a deadlock when stopping and handling an event at the same time.

Fix local watcher deadlock

---

client/test/backend.go

This PR includes a small update to the mock subscription. Storing a context in a struct is disadvised and not needed here as we can just rely on the functionality of the events channel.

MockBackend: Remove context from subscription

---

channel/multi/subscription.go
client/test/multiledger_dispute.go

Fix Multi-Adjudicator Subscription

---

channel/machine.go
client/adjudicate.go

If a ForceUpdate fails, the channel may remain in state `Progressing`.
With this change we allow for retrying from this phase.

Allow retry Channel.ForceUpdate

---

wire/net/simple/account.go
wire/net/simple/address.go
wire/net/simple/address_test.go
wire/net/simple/init.go

A string-based address type implementation.
Depends on #373.

Add default wire.Address type

---

README.md

README: Fix link to white paper

---

channel/adjudicator.go
channel/machine.go
client/adjudicate.go
client/test/bob.go
client/test/channel.go
client/test/fund.go
client/test/multiledger_dispute.go
client/test/multiledger_happy.go
client/test/persistence.go
client/test/progression.go
client/test/subchannel.go
client/test/virtualchannel.go
watcher/local/watcher.go

This PR removes the settle secondary logic. It was not well documented and rarely used, and lead to confusion. We can still implement the same functionality on the application level if necessary.
Closes #81

Remove settle secondary

---

wire/protobuf/wire.proto

This allows including `wire.proto` in other projects and generates the correct include paths in .proto modules including it.
Signed-off-by: Steffen Rattay <steffen@perun.network>

wire.proto: use absolute module path

---

wire/protobuf/proposalmsgs.go
wire/protobuf/syncmsgs.go
wire/protobuf/updatemsgs.go

Signed-off-by: Steffen Rattay <steffen@perun.network>

Expose protobuf converters

---

.golangci.yml
client/transparentchannel.go

This PR adds a new channel wrapper `TransparentChannel` that grants access to the channel's `SignedState`.
In the context of light clients using the Perun WebSocket, the ability to send them the signed state of their channel as a backup allows the light clients to register the channel on-chain even if the WebSocket should be offline.

Grant access to SignedState

---

MAINTAINERS.md
NOTICE
channel/test/app_randomizer.go
channel/test/app_randomizer_internal_test.go
channel/test/mock_app_randomizer.go
go.mod
go.sum
wire/net/simple/init.go

This PR serves to fix the #395 issue of failing unit tests. 
Location: `channel/test/app_randomizer_internal_test.go`
Cause: The issue stems from the lack of Comparator (`Equal`) for MockAppRandomizer. This leads to the test not recognizing that the default appRandomizer has already been set in the internal test.
Solution: Add an identifier to the MockAppRandomizer to compare the old and new appRandomizer.
Location: (`wire/net/simple/dialer_internal_test.go`)
Cause: Like @RmbRT has pointed out, there is a race between the init of `wire/simple` and `backend/sim/wire`, which set the RandomAddress and RandomAccount functions to be used in the internal tests.
Solution: Add the initialization of `NewRandomAddress` and `NewRandomAccount` to use the implementation from the `wire/simple`. …

#395_Fix_Falling_Unit_Tests

---

go.mod
go.sum

This PR bumps the go version to 1.22
Update go version from 1.17 to 1.22

chore: update go to 1.22

---

README.md

This adds support for the Stellar backend in the README.

Add(README): Add Stellar backend support in README.

---

.github/workflows/ci.yml
NOTICE

Updates to the latest actions cache.
Check that actions/cache@v4 works for you.
Per [GitHub](https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/) versions 1 and 2 will go offline 01 FEB 2025.

chore: update action cache

---

wire/account.go
wire/net/exchange_addr.go
wire/net/simple/address.go
wire/net/simple/dialer_internal_test.go
wire/net/simple/simple_exchange_addr_test.go
wire/test/msgstest.go

This PR fix the bug #421 by removing the hard-coded test-backend signature from AuthMsg and required the user to sign all of the address map using all of there backends.
`wire/net` package 
This implementation increase the number of authentication msgs by the number of backends (log(n)) and could cause performance issues with a large number of backends.
Signed-off-by: Minh Huy Tran <huy@perun.network>

fix(wire/net): remove test backend signature from authMsg of exchange address protocol

---

CHANGELOG.md
README.md

This PR updates the `CHANGELOG` with features for the minor release `v0.14.1`, which includes:
* PR [423](https://github.com/hyperledger-labs/go-perun/pull/423): Extend go-perun testing framework.
* Updates `README.md` to document the supported Backends and their IDs for cross-chain functionality #427 .

Minor Release v0.14.1
