.github/workflows/ci.yml
CHANGELOG.md
README.md
apps/doc.go

Update all links to the new HLL repo.  
Codeclimate is removed since it is not setup for this project.

:memo: Update links to HyperLedger Labs.

---

backend/ethereum/wallet/simple/transactor.go
backend/ethereum/wallet/simple/wallet.go

🐛 [backend/ethereum/wallet/simple] Unexported and protected accounts

---

backend/ethereum/channel/adjudicator.go
backend/ethereum/channel/contractbackend.go
backend/ethereum/channel/deploy.go
backend/ethereum/channel/erc20_depositor.go
backend/ethereum/channel/errors.go
backend/ethereum/channel/eth_depositor.go
backend/ethereum/channel/funder.go
backend/ethereum/channel/withdraw.go
client/errors.go
client/proposal.go
client/watch.go

Add Named errors tx timed out

---

.github/workflows/ci.yml

Speed-up CI

---

backend/ethereum/channel/timeout_test.go
backend/ethereum/channel/withdraw.go

Closes #49 
Also fixing a nil context warning.

49 fix variable capture

---

backend/ethereum/channel/erc20_depositor.go
backend/ethereum/channel/eth_depositor.go
backend/ethereum/channel/funder.go
backend/ethereum/channel/funder_test.go
backend/ethereum/channel/test/setup.go
channel/persistence/keyvalue/restorer.go
client/proposal.go
client/test/subchannel.go

Simplify funder interface

---

backend/ethereum/bindings/abi.go
backend/ethereum/bindings/doc.go
backend/ethereum/channel/funder.go
backend/ethereum/channel/withdraw.go

Expose BoundContracts ABI

---

backend/ethereum/channel/adjudicator.go
backend/ethereum/channel/asset.go
backend/ethereum/channel/conclude.go
backend/ethereum/channel/contractbackend.go
backend/ethereum/channel/deploy.go
backend/ethereum/channel/erc20_depositor.go
backend/ethereum/channel/errors/doc.go
backend/ethereum/channel/errors/errors.go
backend/ethereum/channel/eth_depositor.go
backend/ethereum/channel/funder.go
backend/ethereum/channel/subscription.go
backend/ethereum/channel/timeout.go
backend/ethereum/channel/txtypes.go
backend/ethereum/channel/withdraw.go

Create and Use [eth/channel/errors] 

---

backend/ethereum/channel/funder.go
backend/ethereum/subscription/eventsub.go
backend/ethereum/subscription/eventsub_test.go

Merge EventSub.{ReadAll|ReadFuture} into Read

---

client/proposal.go

:bug: [client] Defer release version 1 cache

---

backend/ethereum/subscription/eventsub.go

Using a `[pkg/sync] Closer` makes the `EventSub.Close()` call idempotent and easier to use.
Closes #161

Make EventSub a Closer

---

.github/workflows/ci.yml

:construction_worker: [CI/github] Use caching

---

pkg/errors/gatherer.go
pkg/errors/gatherer_test.go

Closes #181  
Need this for testing, @RmbRT also seems to appreciate it.

[pkg/errors] Add Gatherer DoneOrFailed(Ctx)

---

.github/ISSUE_TEMPLATE/issue.md

Adding a simple issue template

Create issue template

---

channel/test/channeltest.go

[channel/test] Generate modified params with correct id

---

.github/ISSUE_TEMPLATE/basic.md

When creating a new issue, the template description looked a bit odd. Hence, adjusting.

Update and rename issue.md to basic.md

---

.github/ISSUE_TEMPLATE/basic.md

Issue templates must have an about text.

Fix basic issue template

---

backend/ethereum/channel/conclude_test.go
backend/ethereum/channel/contractbackend.go
backend/ethereum/channel/init_test.go

:bug: Prevent confirmNTimes from blocking indefinitely

---

backend/sim/wallet/wallet.go
client/adjudicate.go
client/client_role_test.go
client/dispute_test.go
client/happy_test.go
client/init_test.go
client/subchannel_dispute_test.go
client/subchannel_happy_test.go
client/test/backend.go
client/test/proposer.go
client/test/responder.go
client/test/subchannel_dispute.go
client/virtual_channel_test.go
watcher/local/watcher.go

Closes #251 
Maybe add tests for watching sub-channels. We only test watching ledger channels.

:bug: [client] Start watching for sub-channel

---

.golangci.yml
apps/payment/app_internal_test.go
apps/payment/randomizer_internal_test.go
apps/payment/resolver_internal_test.go
backend/ethereum/wallet/address.go
backend/ethereum/wallet/backend.go
backend/sim/wallet/address.go
channel/app.go
channel/appregistry_internal_test.go
channel/persistence/test/channel.go
channel/persistence/test/persistrestorertest.go
client/adjudicate.go
client/client.go
client/proposal.go
client/proposal_internal_test.go
client/subchannel.go
client/test/role.go
wallet/address.go
wallet/address_test.go
wallet/test/address.go
wire/address.go
wire/net/endpoint_internal_test.go
wire/net/endpoint_registry.go
wire/net/endpoint_registry_external_test.go
wire/net/exchange_addr.go
wire/net/exchange_addr_internal_test.go
wire/net/test/listenermap.go
wire/test/bustest.go

Rename Address.Equals to Equal

---

.github/workflows/ci.yml

Just a minor update to the CI workflow.

CI: Update workflow after changing from dev to main

---

log/log.go

log: Add comments to logger interfaces

---

.golangci.yml
backend/sim/wallet/address.go
backend/sim/wallet/address_internal_test.go
backend/sim/wallet/wallet_internal_test.go

Lint comments on exported objects (functions, types, ...)

---

backend/ethereum/channel/adjudicator_test.go
backend/ethereum/channel/asset.go
backend/ethereum/channel/backend.go
backend/ethereum/channel/conclude_test.go
backend/ethereum/channel/erc20_depositor.go
backend/ethereum/channel/eth_depositor.go
backend/ethereum/channel/funder.go
backend/ethereum/channel/funder_test.go
backend/ethereum/channel/register_test.go
backend/ethereum/channel/test/randomizer.go
backend/ethereum/channel/test/setup.go
backend/ethereum/channel/withdraw.go
backend/ethereum/channel/withdraw_test.go
backend/ethereum/client/dispute_test.go
backend/ethereum/client/happy_test.go
backend/ethereum/client/progression_test.go
backend/sim/channel/asset.go
channel/allocation.go
pkg/io/bigint_external_test.go
pkg/io/byteslice_external_test.go
pkg/io/equal_encoding_external_test.go

Introduce and use Asset.Equal

---

backend/sim/channel/asset.go

- Previously, pkgio.(Encode|Decode) methods were used for
marshallign/unmarshalling the Asset. This coupled the asset to a
specific serialization implementation (pkg/io).
- Instead, use binary.BigEndian.Putuint64 directly.
Closes #283

Use fixed length format for (un)marshalling asset

---

README.md
client/subchannel.go
client/test/channel.go
client/update.go
client/update_internal_test.go
client/virtual_channel_test.go

💥 Rename `Channel.Update`

---

channel/allocation.go
channel/machine.go
client/proposal.go
client/virtual_channel.go
client/virtual_channel_settlement.go

303 check assets

---

backend/ethereum/channel/contractbackend.go

eth/channel: Fix tx receipt pulling

---

client/proposal.go
client/subchannel.go

client: Export proposer and proposee index

---

channel/allocation.go

Fixes a bug where balances were not initialized to zero.

channel: Init balances to zero

---

README.md

Improves the README:
- Adds information about more available blockchain backends.
- Adds information about available documentation and code examples.

Readme update backends

---

client/syncmsgs_test.go
client/updatemsgs_test.go

- These tests were missing.
Signed-off-by: Manoranjith <ponraj.manoranjitha@in.bosch.com>

Add missing tests for sync msg serialization

---

go.mod
go.sum
wire/hybridbus.go
wire/hybridbus_test.go
wire/localbus_test.go
wire/net/bus_test.go
wire/test/bustest.go

Enables perun-network/perun-websocket-backend#2.

Wire hybrid bus

---

CHANGELOG.md

Changelog. Afterwards set tag on merge commit.

Release 0.9.1

---

CHANGELOG.md
README.md

Updates the CHANGELOG for release v0.10.0.

Update CHANGELOG v0.10.0

---

channel/multi/adjudicator.go

Add Adjudicator Getter for Multi-Adjudicator

---

client/client_test.go
client/proposal.go

Channel proposal rejection was not working correctly, as the wrong message type was checked.

Fix proposal reject

---

client/test/virtualchannel.go
client/virtual_channel_test.go

This makes the test reusable for different backends.

Abstract virtual channel test

---

client/test/role.go

Fix NewClients

---

apps/payment/app.go
apps/payment/app_internal_test.go
apps/payment/randomizer.go
apps/payment/resolver.go
apps/payment/resolver_internal_test.go
backend/sim/channel/app.go
backend/sim/channel/asset_test.go
backend/sim/channel/backend.go
backend/sim/channel/init.go
channel/app.go
channel/appregistry.go
channel/appregistry_internal_test.go
channel/backend.go
channel/mock_app.go
channel/mock_app_internal_test.go
channel/noapp.go
channel/test/app_randomizer.go
channel/test/mock_app_randomizer.go
channel/test/randomopts.go
client/appchannel_test.go
wallet/address.go
wire/protobuf/init_test.go
wire/protobuf/proposalmsgs.go
wire/protobuf/serializer_test.go

Create app id type

---

NOTICE
wire/protobuf/proposalmsgs.go
wire/protobuf/serializer.go
wire/protobuf/syncmsgs.go
wire/protobuf/updatemsgs.go

This exposes existing converters between protobuf types and various go-perun types.

Expose protobuf converters

---

CHANGELOG.md

This updates the changelog to reflect the changes introduced by v0.12.0.

Chore(CHANGELOG): Update changelog to v0.12.0
